### ISSUE TITLE
synouidmod - User not found

### ISSUE THREAD

**Issue by vigri** [sunnyone/synouidmod#2]
Hello @sunnyone,

I've been able to successfully compile `synouidmod` (Target: DSM 6.2, Plattform apollolake).

However, `synouidmod` doesn't seem to work.

No matter which user I pass as an argument, the errror is always `User XYZ is not found`

#### command
```
void@nas:/volume1/test$ sudo ./synouidmod plex
User 'plex' is not found.
```

#### /etc/shadow
```
plex:$XXXXXXXX/:17690:0:99999:7:::
```

Am I doing something wrong or is this a bug?

**Comment by vigri** [comment]
My mistake... username has to be uppercase.
I'll submit a PR with some enhancements.

**Comment by sunnyone** [comment]
Thanks for the report!
